### ISSUE TITLE
cant find every picture.

### ISSUE THREAD

**Issue by osevan** [rosuH/EasyWatermark#136]
Easywatermark cant find custom createdfolder pics.

Only in galary saved pics

And inside Easywatermark no file Explorer exist.

Hope you can fix.

**Comment by rosuH** [comment]
I will add system's images picker in next release.

**Comment by osevan** [comment]
> I will add system's images picker in next release.

Thank you very much!!!!

**Comment by osevan** [comment]
Could you update me here,when you are ready?

**Comment by rosuH** [comment]
Of course.

**Comment by osevan** [comment]
I have a new app idea,Because no app exist outside for this purpose. 

Easy videomark " batch video watermarking mass of videos with one click "

But important part is: watermark need to move from bottom to up amd reverse, from up to down.

I know its possible with ffmpg,but,how you can plant thus I dunno.


Thanks and

Best regards

**Comment by rosuH** [comment]
> Could you update me here,when you are ready?

Try the v2.6.6 pls.
