### ISSUE TITLE
文字大小的预览效果与实际效果不一致

### ISSUE THREAD

**Issue by sakuyamaij** [rosuH/EasyWatermark#14]
比如字号48
预览估计是在缩小过的预览图上加上字号48的文字

生成图片的实际效果则是在原图分辨率上加上字号48的文字，显得字非常小

这里还是建议和预览效果一致比较好

**Comment by rosuH** [comment]
是有这个问题，您说到点子上了。目前有在考虑这个如何优化。

感谢反馈~

**Comment by rosuH** [comment]
@sakuyamaij 你好，新版本对文字大小做了处理，可以尝试下。感谢反馈~
