### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by pythonInRelay** [rosuH/EasyWatermark#145]
The button to select an image says "Selecte"

It's actually "Select" in English.

I think it would be better to have it say: "Choose Images"

As it is simpler English, plus you can pick more than one image for watermarking. So it just makes more sense.

Thanks a lot for making the app <3
No one is gonna share a photo I don't want, if I watermark their phone number all over it hahahahaha.

**Comment by rosuH** [comment]
haha, that's a low-level spelling mistake.
