### ISSUE TITLE
[bug]红米K30 Pro导入高度比宽度大的图片后图片自动旋转

### ISSUE THREAD

**Issue by lyc0209** [rosuH/EasyWatermark#148]
如图，左边是红米k30 Pro，系统`MIUI13 V13.0.1.1.11.DEV`，右边是小米5，系统`PixelExperience_Plus_gemini-11.0-20211216-1610-OFFICIAL`。
导入同一张高度比宽度大的图片，右侧手机显示正常，左侧图片旋转了90度。左侧手机导出后图片依然是旋转90度的。

另外我是个尝试写过一些Android App的前端码农，看了你的代码，自定义View让我醍醐灌顶！
很棒的软件，作者辛苦了

![e6d3ddd981499d6f1de4778f37e04d7](https://user-images.githubusercontent.com/51283456/156872726-ec706a9d-9195-4480-8d55-35cb423e8c9b.jpg)

**Comment by rosuH** [comment]
如果方便的话，可以把照片打成压缩包然后发邮件给我吗？可能和照片信息有关~

邮箱：hi@rosuh.me

**Comment by lyc0209** [comment]
> 如果方便的话，可以把照片打成压缩包然后发邮件给我吗？可能和照片信息有关~
> 
> 邮箱：[hi@rosuh.me](mailto:hi@rosuh.me)

好的，已发送。可能真的和图片信息有关，经过测试，这两张图片在右侧的小米5中也会复现该bug，之前表述有误(之前图片通过qq发送到小米5上，经过压缩，没有出现该bug。刚才我将原图在小米5上打开会出现该bug)。

**Comment by rosuH** [comment]
2.6.8 版本已经修复该问题，欢迎体验和反馈，感谢~
