### ISSUE TITLE
无法显示预览

### ISSUE THREAD

**Issue by wong077** [rosuH/EasyWatermark#20]
中兴天机9，安卓9， 1.1.0版，导入图片后无法显示预览，但能导出图片

**Comment by rosuH** [comment]
@wong077 

- 水印有出现吗？还是水印和图片全都没有显示呢？
- 全部图片都不行是嘛？还是只有单张不行。

**Comment by rosuH** [comment]
已在 1.1.1 修复，请尝试新版本～
