### ISSUE TITLE
隐私政策中的联系邮箱不匹配

### ISSUE THREAD

**Issue by Young-Lord** [rosuH/EasyWatermark#200]
RT，显示的是`rosuh＠qq.com`，而超链接指向的是`hi@rosuh.me`
根据提交历史来看，貌似应该改为`hi@rosuh.me`？

具体来说是这两处：
https://github.com/rosuH/EasyWatermark/blob/master/PrivacyPolicy_zh-CN.md?plain=1#L6
https://github.com/rosuH/EasyWatermark/blob/master/PrivacyPolicy.md?plain=1#L13

**Comment by rosuH** [comment]
感谢指正，起初替换邮箱确实不是很彻底。😂
