### ISSUE TITLE
可选输出质量和水印位置偏移问题

### ISSUE THREAD

**Issue by ellermister** [rosuH/EasyWatermark#25]
非常不错，已经用了好几次了，有个小疑问：
1. 我 1M的图片，加完水印，变7M，这个好大呀，还得手动压缩裁切下。
2. 预览的水印位置和实际导出后的不一样，不过都不影响使用，多导几次就好了。

**Comment by rosuH** [comment]
- 输出设置：在做了在做了（[新建了个文件夹](https://github.com/rosuH/EasyWatermark/projects/1#card-45011266)）
- 水印偏移问题暂时没有一劳永逸的办法，短期内不会完美解决。

感谢反馈～

**Comment by rosuH** [comment]
你好，输出质量选项已经在新版（2.0.0）加上。水印偏移问题亦有所改善，欢迎体验~
