### ISSUE TITLE
Idiom

### ISSUE THREAD

**Issue by leogbar** [rosuH/EasyWatermark#28]
Please add spanish to traductions

**Comment by rosuH** [comment]
Do you mean `README`?

**Comment by leogbar** [comment]
No, I don't reference to a readme, to the app, then I see that spanish is a option lenguage, but the app how I installed only see in chinese and not can change the language to spanish

El 17 de octubre de 2020 7:54:21 UTC, rosuH <notifications@github.com> escribió:
>Do you mean `README`?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rosuH/EasyWatermark/issues/28#issuecomment-710769067
-- 
Leonardo Barenghi

**Comment by rosuH** [comment]
I see...This app does not provide language change options for now. The UI language would only change with your System's language. Maybe your System language was set to Chinese? 😂
