### ISSUE TITLE
2.8.8版本 添加贴纸水印Bug

### ISSUE THREAD

**Issue by valianliu** [rosuH/EasyWatermark#289]
如标题。添加贴纸水印，平铺格式选择单个，预览正常。但生成的图片就是按照重复的排列添加的水印
版本2.8.8
系统MIUI14
设置页面截图：
![Screenshot_2023-07-26-23-04-12-494_me rosuh easywatermark](https://github.com/rosuH/EasyWatermark/assets/9492905/25a5536e-dde9-43c2-a302-8de6a5cb1117)
生成的图片：
![ewm_1690383676271](https://github.com/rosuH/EasyWatermark/assets/9492905/43faa503-8616-4796-9a38-3dd76b240e65)
初步判断是bug，期待修复😂
感谢开发

**Comment by rosuH** [comment]
有什么复现路径吗

**Comment by valianliu** [comment]
> 

我的操作流程如下：
开软件选图，
选贴纸，图片用的是存好在手机里的透明的PNG图，
样式，平铺格式，选单个，简单调整位置和大小，看预览图如截图1，然后输出格式JPG，质量 100，导出来的完成图就是平铺效果不是单个的。如果有必要我可以试着录屏传到个网盘？

**Comment by rosuH** [comment]
谢谢，有录屏的话会更好:D

**Comment by valianliu** [comment]
> 

又试了几次，大概定位到问题了！
是出现在选择多个文件的情况下，第一张调整成了单个贴纸，但其他的多选文件并没有联动，导致后边的其他文件都是默认的 重复。
我想这里边可能涉及到一个逻辑，如果用户多选了文件，基本是想偷懒套用一样的水印样式吧，单张的设置应该套用给其他多选上的图😂

**Comment by rosuH** [comment]
谢谢！这样的设计是故意的（
主要考虑到用户可能混合设置，所以没有同步整个列表的模式。🌚

**Comment by valianliu** [comment]
> 谢谢！这样的设计是故意的（
> 主要考虑到用户可能混合设置，所以没有同步整个列表的模式。🌚

我设想的逻辑可能略有不同：
选多张照片的用户应该大多数是想一起设置水印，即同一个规格和样式的水印套用到多选的这一组多张图片上，单张样式用户操作优先会用单独选图进行编辑把？
多选的情况下，想单独为每张设置不同的水印，按照正常思维逻辑，这种目的应该是少数。
所以是否这个多选后，默认为多张套用同一个水印样式，单张有具体需求可以单独去调整，这样的设定是否更优，更符合用户思考路径和使用逻辑呢。
目前多选后，还不能默认套用同一个水印设置，逻辑上多少有点奇怪😆
这大概是我的思考，仅供参考，谢谢。

**Comment by valianliu** [comment]
另外我发现多选图片的编辑状态下，布局里，水印位置的设置，默认是套用给所有多选的图，至少为了逻辑上的一致性，样式里的设定是不是也应该保持一致😆

**Comment by rosuH** [comment]
感谢建议，已经在最新版 2.8.9 调整为应用到全部图片，欢迎体验 :D
