### ISSUE TITLE
能否支持 “相册app” 的调用？

### ISSUE THREAD

**Issue by forliuyifei** [rosuH/EasyWatermark#30]
现在选择图片只能从文件管理器选取，在快图浏览里面无论是编辑还是分享功能都找不到这个工具。

**Comment by rosuH** [comment]
你现在是想实现什么需求呢？

**Comment by forliuyifei** [comment]
> 你现在是想实现什么需求呢？

让入口更简单易用，现在只能特地打开app添加水印，应该在相册查看某张照片的时候直接可以调用这个软件进行编辑。

**Comment by rosuH** [comment]
@forliuyifei 非常棒的想法，感谢反馈~

**Comment by rosuH** [comment]
你好，新版本已经支持，欢迎体验。

**Comment by forliuyifei** [comment]
> 你好，新版本已经支持，欢迎体验。

好耶
