### ISSUE TITLE
在 一加 7T Pro上不能导出到相册

### ISSUE THREAD

**Issue by Cye3s** [rosuH/EasyWatermark#337]
一加 7T Pro 是 OxygenOS 12，已不能再更新，Android主版本为12。
软件是从GitHub下的最新版本，已也允许访问媒体文件，能选择图片。
但导出到相册时提示“获取权限失败”。

只能用触摸屏有一列失灵的一加 9 Pro 5G处理得到最后的图片，OxygenOS 14。

**Comment by rosuH** [comment]
试试 2.9.4
