### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by serrq** [rosuH/EasyWatermark#339]
Water 2.9.4 Izzy
Android 14
OnePlus CPH2399

![1000120150](https://github.com/user-attachments/assets/31824b20-5328-41ea-8552-addcbd6c19f7)

**Comment by rosuH** [comment]
try the 2.9.5 pls

**Comment by rosuH** [comment]
> I stay in fdroid.

then you will probably have to wait a few days, as F-droid has its own build schedule.
