### ISSUE TITLE
图片自动旋转导致预览和生成的照片不一致

### ISSUE THREAD

**Issue by guoyiang** [rosuH/EasyWatermark#41]
我的手机是三星S10+，在使用时发现手机拍摄照片存储的方像和拍摄方向不同。比如前置摄像头竖直拍摄的时候，存储的照片是横向比较长，但是实际显示和拍摄的时候是纵向长。在相册内预览的时候手机做了自动旋转，程序内预览的效果也是旋转后的。但是生成的图片没有考虑自动旋转，导致预览和实机照片的效果不一样。
希望在预览和生成图片的时候考虑进图片的自动旋转问题。

另外谢谢您开发和维护这个程序

**Comment by rosuH** [comment]
感谢反馈，我会尽快确认这个问题。不过因为手头没有三星设备，到时候可能需要您帮忙确认啦:grin:
