### ISSUE TITLE
[功能请求]两个小建议

### ISSUE THREAD

**Issue by xushet** [rosuH/EasyWatermark#43]
1，布局能够支持负数调整或者更小的布局，我把水平垂直布局拉到0还是感觉间隙有点大，原因是想让水印更密集一点
2，（不是很需要）支持多重水印，比如添加了一句请勿他用的声明后，有时还需要添加时间戳水印，所以时间戳功能拜托了

很棒的软件！

**Comment by rosuH** [comment]
感谢反馈~间距问题之前有考虑调整，但是还没做哈哈，后续会加上的。时间戳可以考虑~
